### ISSUE TITLE
pocesar- i need your help with actor facebook scraper

### ISSUE THREAD

**Issue by Reyna22222** [pocesar/actor-facebook-scraper#15]
You can add at scraper  "scrapePageTransparency"  and receive if have curently ads or not?
Please let me know. Thank you

**Comment by pocesar** [comment]
hello @Reyna22222 yes, this can be added

**Comment by Reyna22222** [comment]
Hi Paulo,
After you add the section, can update on apify?
Thanks

**Comment by pocesar** [comment]
yup

**Comment by Reyna22222** [comment]
OK Paulo, 
Please let me know after you will done. Thank you

**Comment by pocesar** [comment]
@Reyna22222 it seems to display the page transparency you need to be logged in, so it won't be able to be implemented as of now
