### ISSUE TITLE
TimeoutOverflowWarning: 2574000000 does not fit into a 32-bit signed integer.

### ISSUE THREAD

**Issue by metalwarrior665** [pocesar/actor-facebook-scraper#3]
2020-05-11T20:48:43.634Z (node:27) TimeoutOverflowWarning: 2574000000 does not fit into a 32-bit signed integer.

Happens when you set more than 9999 comments

**Comment by pocesar** [comment]
the timeout is exponential to the number of comments you choose, I need to make it more clear on the README, there's a shy mention for warning on `maxPosts` there in https://github.com/pocesar/actor-facebook-scraper#expected-consumption

**Comment by pocesar** [comment]
should throw now, although I couldn't reproduce using 9999, was much bigger
