### ISSUE TITLE
extract profile and banner image

### ISSUE THREAD

**Issue by terchris** [pocesar/actor-facebook-scraper#34]
It would be great if the script could also include the url to the profile image and the banner image (or video).

I'm doing this myself by looking at the images and their with.
The profile  image has a with of 172 and the larger profile a with of 500

I would rather use your scraper than maintaining my own. So if you could include this it would be great.

**Comment by pocesar** [comment]
@terchris I've added it to the README on how to do it:

https://github.com/pocesar/actor-facebook-scraper#extend-scraper-function

you can add the video there too. notice that is the the mobile version of the page, not the desktop
