### ISSUE TITLE
Can I use it for facebook marketplace?

### ISSUE THREAD

**Issue by yardenshoham** [pocesar/actor-facebook-scraper#6]
I'd like to, for example, get all vehicle offerings in a given city. Is it possible?
@pocesar

**Comment by pocesar** [comment]
hello @yardenshoham, it's not currently possible, but it's a possibility in the future, since it's publicly available

**Comment by metalwarrior665** [comment]
I think Facebook Marketplace would be better as a standalone actor

**Comment by metalwarrior665** [comment]
Let's make the FB marketplace as a separate scraper.
