### ISSUE TITLE
console.dir(run.output); returns null

### ISSUE THREAD

**Issue by r-bechara** [pocesar/actor-facebook-scraper#7]
After trying the sample code provided at https://apify.com/pocesar/facebook-pages-scraper, I noticed that the last following lines return null. Asynchronous call also return null.

const run = await Apify.call('pocesar/facebook-pages-scraper', input, options );
console.dir(run.output);

The result data is available for download at "apify" site, therefore it doesn't return when calling from Node.

**Comment by pocesar** [comment]
hey @r-bechara indeed, the Facebook scraper doesn't have an OUTPUT on the KV store, you need to access the defaultDatasetId and fetch the items

**Comment by r-bechara** [comment]
Thank you! I noticed it later. It worked when I accessed the result via "URL".

**Comment by metalwarrior665** [comment]
This is a bug on Apify's side which will be fixed later, nothing required for this scraper.
